DISCOVERY_QUERIES: list[str] = [
    '"external audit services" Rwanda',
    '"external audit" Rwanda tender',
    '"audit firm" Rwanda request for proposal',
    '"qualified audit firms" Rwanda',
    '"statutory audit services" Rwanda',
    '"internal audit services" Rwanda',
    '"project audit" Rwanda request for proposal',
    '"financial audit services" Rwanda',

    '"accounting firm" Rwanda tender',
    '"accounting services" Rwanda request for proposal',
    '"bookkeeping services" Rwanda',
    '"financial reporting services" Rwanda',
    '"IFRS consultancy" Rwanda',
    '"IPSAS consultancy" Rwanda',

    '"tax advisory services" Rwanda tender',
    '"tax consultancy" Rwanda request for proposal',
    '"tax compliance services" Rwanda',

    '"recruitment firm" Rwanda tender',
    '"recruitment services" Rwanda request for proposal',
    '"human resources consultancy" Rwanda',
    '"payroll services" Rwanda tender',

    '"consulting firm" Rwanda expression of interest',
    '"consultancy firm" Rwanda request for proposal',
    '"professional services firm" Rwanda tender',
    '"financial management services" Rwanda tender',
    '"risk management consultancy" Rwanda',
    '"governance consultancy" Rwanda',
    '"due diligence" Rwanda consultancy',
    '"capacity building" Rwanda consultancy',
    '"institutional assessment" Rwanda consultancy',

    '"request for proposal" Rwanda consulting firm',
    '"expression of interest" Rwanda professional services',
    '"request for quotation" Rwanda consultancy',
    '"terms of reference" Rwanda consulting firm',
    '"qualified firms" Rwanda proposals',
    '"framework agreement" Rwanda consultancy',
    '"prequalification of service providers" Rwanda',

    'site:.rw tender consultancy',
    'site:.rw procurement opportunities',
    'site:.rw "request for proposal"',
    'site:.rw "expression of interest"',
    'site:.rw "terms of reference" consultancy',
    'site:.rw "qualified firms" proposals',
    'site:.rw "audit services"',
    'site:.rw "accounting services"',
    'site:.rw "recruitment services"',

    'site:.org.rw request for proposal',
    'site:.org.rw tender consultancy',
    'site:.org.rw external audit',
    'site:.co.rw tender services',
    'site:.co.rw procurement opportunities',
    'site:.gov.rw tender consultancy',
    'site:.gov.rw request for proposal',
]